/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import conexiones.Datosalmacenados;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raulsantiago
 */
public class Bibliotecaprincipal extends javax.swing.JFrame {

    Datosalmacenados datos = null;
    
    Bibliotecaprincipal(){}

    public Bibliotecaprincipal(Datosalmacenados datos) {

        this.datos = datos;
        initComponents();
        ponerenTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPrincipal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15"
            }
        ));
        jScrollPane2.setViewportView(TablaPrincipal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    //Otras variables
     public void ponerenTabla() {
        
         
          DefaultTableModel modelo = (DefaultTableModel) TablaPrincipal.getModel();

        //Recorre el listado de aviones del vector de aviones del aeropuerto de la clase <Control>
        for (int i = 0; i < datos.listado.size(); i++) {

            //Se crea un Array para almacenar la matrícula, origen y destino del <avión>
            String[] lista = new String[15];

           
            //Rellena el array con la información obtenida
            lista[0] = datos.listado.get(i).getTitulo();
            lista[1] = datos.listado.get(i).getAutor();
            lista[2] = datos.listado.get(i).getRevista();
            lista[3] = datos.listado.get(i).getEditorial();
            lista[4] = datos.listado.get(i).getCategoria();
            lista[5] = String.valueOf(datos.listado.get(i).getNrevista());
            lista[6] = String.valueOf(datos.listado.get(i).getAño());
            lista[7] = datos.listado.get(i).getISBN();
            lista[8] = datos.listado.get(i).getLugar();
            lista[9] = datos.listado.get(i).getDeposito_legal();
            lista[10] = datos.listado.get(i).getEstante();
            lista[11] = datos.listado.get(i).getUbicacion();
            lista[12] = datos.listado.get(i).getSignatura();
            lista[13] = datos.listado.get(i).getObservaciones();
            lista[14] = datos.listado.get(i).getInforme();

            
            //Añade el array a la fila de la tabla
          modelo.addRow(lista);
            

        }
        
        TablaPrincipal.setModel(modelo);

    }
}
