/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import javax.swing.JOptionPane;
import conexiones.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raulsantiago
 */
public class PanelCargaInicial extends javax.swing.JFrame {

    MySQL datos = new MySQL();

    /**
     * Creates new form NewJFrame
     */
    public PanelCargaInicial() {
        initComponents();

        panelFiltro.setVisible(false);
        PanelMenu.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        panelIzq = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        clave = new javax.swing.JPasswordField();
        textoClave = new javax.swing.JLabel();
        botonValidar = new javax.swing.JButton();
        panelRojoInfo = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        muestraTitulo = new javax.swing.JLabel();
        labelAutor = new javax.swing.JLabel();
        muestraAutor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        muestraEditorial = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        muestraCategoria = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        muestraAno = new javax.swing.JLabel();
        labelISBN = new javax.swing.JLabel();
        labelLugar = new javax.swing.JLabel();
        muestraLugar = new javax.swing.JLabel();
        labelDepLegal = new javax.swing.JLabel();
        muestraDepLegal = new javax.swing.JLabel();
        labelUbicacion = new javax.swing.JLabel();
        muestraUbicacion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        muestraISBN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        labelRevista = new javax.swing.JLabel();
        muestraRevista = new javax.swing.JLabel();
        labelNRevista = new javax.swing.JLabel();
        muestraNRevista = new javax.swing.JLabel();
        labelEstante = new javax.swing.JLabel();
        muestraEstante = new javax.swing.JLabel();
        labelSignatura = new javax.swing.JLabel();
        muestraSignatura = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelFiltro = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        opcionCombo = new javax.swing.JComboBox<>();
        fieldCriterio = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        botonResetFiltro = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        panelSalida = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrincipal = new javax.swing.JTable();

        jDialog1.setTitle("Ajustes");
        jDialog1.setBackground(new java.awt.Color(45, 64, 89));

        jPanel4.setBackground(new java.awt.Color(45, 64, 89));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SanBiblioteca");
        setBackground(new java.awt.Color(153, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        panelIzq.setBackground(new java.awt.Color(45, 64, 89));
        panelIzq.setForeground(new java.awt.Color(255, 255, 255));
        panelIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Kefa", 3, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 205, 195));
        jLabel5.setText("Created by: Raul Santiago Prieto.2020");
        panelIzq.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        panelTitulo.setBackground(new java.awt.Color(222, 205, 195));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-books-48.png"))); // NOI18N
        panelTitulo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        titulo.setFont(new java.awt.Font("Kohinoor Telugu", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(45, 64, 89));
        titulo.setText("SANBIBLIOTECA");
        panelTitulo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        panelIzq.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 330, -1));

        PanelMenu.setBackground(new java.awt.Color(45, 64, 89));

        jLabel6.setFont(new java.awt.Font("Kohinoor Telugu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(229, 229, 229));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-add-database-25.png"))); // NOI18N
        jLabel6.setText("Nuevo libro");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(45, 64, 89));

        jLabel7.setBackground(new java.awt.Color(45, 64, 89));
        jLabel7.setFont(new java.awt.Font("Kohinoor Telugu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(229, 229, 229));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-note-25.png"))); // NOI18N
        jLabel7.setText("Notas");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(45, 64, 89));

        jLabel8.setFont(new java.awt.Font("Kohinoor Telugu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(229, 229, 229));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-buying-25.png"))); // NOI18N
        jLabel8.setText("Compra de libro");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelIzq.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 330, 270));

        PanelLogin.setBackground(new java.awt.Color(45, 64, 89));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clave.setText("Clavedeacceso");
        clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                claveKeyPressed(evt);
            }
        });
        PanelLogin.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 30));

        textoClave.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        textoClave.setForeground(new java.awt.Color(255, 255, 255));
        textoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-password-48.png"))); // NOI18N
        textoClave.setText("Clave:");
        PanelLogin.add(textoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        botonValidar.setText("Login");
        botonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValidarActionPerformed(evt);
            }
        });
        PanelLogin.add(botonValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        panelIzq.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 330, 119));

        panelRojoInfo.setBackground(new java.awt.Color(230, 84, 89));

        jPanel24.setBackground(new java.awt.Color(230, 84, 89));
        jPanel24.setForeground(new java.awt.Color(229, 229, 229));

        labelTitulo.setForeground(new java.awt.Color(229, 229, 229));
        labelTitulo.setText("Título:");

        labelAutor.setForeground(new java.awt.Color(229, 229, 229));
        labelAutor.setText("Autor:");

        jLabel10.setForeground(new java.awt.Color(229, 229, 229));
        jLabel10.setText("Editorial:");

        labelCategoria.setForeground(new java.awt.Color(229, 229, 229));
        labelCategoria.setText("Categoría:");

        labelAno.setForeground(new java.awt.Color(229, 229, 229));
        labelAno.setText("Año:");

        labelISBN.setForeground(new java.awt.Color(229, 229, 229));
        labelISBN.setText("ISBN:");

        labelLugar.setForeground(new java.awt.Color(229, 229, 229));
        labelLugar.setText("Lugar:");

        labelDepLegal.setForeground(new java.awt.Color(229, 229, 229));
        labelDepLegal.setText("Deposito_Legal:");

        labelUbicacion.setForeground(new java.awt.Color(229, 229, 229));
        labelUbicacion.setText("Ubicación:");

        jLabel9.setForeground(new java.awt.Color(229, 229, 229));
        jLabel9.setText("Informe:");

        jLabel11.setForeground(new java.awt.Color(229, 229, 229));
        jLabel11.setText("Observaciones:");

        jButton3.setText("Abrir");

        jButton4.setText("Abrir");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel24Layout.createSequentialGroup()
                                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(muestraEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(muestraCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(muestraAno, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelUbicacion, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel24Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel24Layout.createSequentialGroup()
                                                .addComponent(muestraAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(268, 268, 268)
                                                .addComponent(labelDepLegal))
                                            .addComponent(labelLugar)
                                            .addComponent(jLabel11)))))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(labelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(muestraISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(muestraUbicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(muestraDepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(muestraLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(124, 124, 124))
            .addComponent(jSeparator1)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addComponent(labelLugar)
                            .addComponent(muestraLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(muestraTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(muestraAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAutor))
                    .addComponent(labelDepLegal)
                    .addComponent(muestraDepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(muestraUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(muestraEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(labelUbicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(muestraCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelAno)
                                    .addComponent(muestraAno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jButton3)))))
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelISBN)
                        .addComponent(muestraISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(230, 84, 89));
        jPanel3.setForeground(new java.awt.Color(229, 229, 229));

        labelRevista.setForeground(new java.awt.Color(229, 229, 229));
        labelRevista.setText("Revista:");

        labelNRevista.setForeground(new java.awt.Color(229, 229, 229));
        labelNRevista.setText("Nº Revista:");

        labelEstante.setForeground(new java.awt.Color(229, 229, 229));
        labelEstante.setText("Estante:");

        labelSignatura.setForeground(new java.awt.Color(229, 229, 229));
        labelSignatura.setText("Signatura:");

        jButton1.setText("Aplicar cambios");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelNRevista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraNRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(364, 364, 364)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelEstante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraEstante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelSignatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraSignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRevista)
                            .addComponent(labelEstante))
                        .addComponent(muestraRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelSignatura)
                        .addComponent(labelNRevista))
                    .addComponent(muestraNRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraSignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRojoInfoLayout = new javax.swing.GroupLayout(panelRojoInfo);
        panelRojoInfo.setLayout(panelRojoInfoLayout);
        panelRojoInfoLayout.setHorizontalGroup(
            panelRojoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRojoInfoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRojoInfoLayout.setVerticalGroup(
            panelRojoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRojoInfoLayout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Kohinoor Telugu", 1, 18)); // NOI18N
        jLabel25.setText("Filtro:");

        jPanel21.setBackground(new java.awt.Color(51, 0, 51));

        opcionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Autor", "Revista", "Editorial", "Categoria", "NRevista", "Ano", "ISBN", "Lugar", "Deposito_legal", "Estante", "Ubicación", "Signatura" }));

        fieldCriterio.setText("Introduzca un criterio de búsqueda...");
        fieldCriterio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCriterioFocusGained(evt);
            }
        });
        fieldCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCriterioKeyPressed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        botonResetFiltro.setText("Reset");
        botonResetFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonResetFiltroMouseClicked(evt);
            }
        });
        botonResetFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(opcionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldCriterio, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonResetFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(botonResetFiltro)))
        );

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(42, 42, 42)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTabla.setBackground(new java.awt.Color(229, 229, 229));

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        panelSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 64, 89));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-cerrar-ventana-25.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-ajustes-25.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-spain-25.png"))); // NOI18N
        jLabel2.setToolTipText("Español");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-usa-25.png"))); // NOI18N
        jLabel13.setToolTipText("English");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-france-25.png"))); // NOI18N
        jLabel14.setToolTipText("Français");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-italy-25.png"))); // NOI18N
        jLabel16.setToolTipText("Italiano");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-germany-25.png"))); // NOI18N
        jLabel15.setToolTipText("Deutch");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/eusk.png"))); // NOI18N
        jLabel17.setToolTipText("Euskara");

        javax.swing.GroupLayout panelSalidaLayout = new javax.swing.GroupLayout(panelSalida);
        panelSalida.setLayout(panelSalidaLayout);
        panelSalidaLayout.setHorizontalGroup(
            panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalidaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 522, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(31, 31, 31))
        );
        panelSalidaLayout.setVerticalGroup(
            panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalidaLayout.createSequentialGroup()
                .addGroup(panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel16))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TablaPrincipal.setBackground(new java.awt.Color(229, 229, 229));
        TablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Revista", "Editorial", "Categoria", "Nº Revista", "Año", "ISBN", "Lugar", "Deposito leg.", "Estante", "Ubicación", "Signatura", "Observaciones", "Informe"
            }
        ));
        TablaPrincipal.setEnabled(false);
        TablaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelRojoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(976, 976, 976))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(panelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(panelRojoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(panelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1201, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        Color colorGanado = new Color(78, 137, 174);
        jLabel8.setBackground(colorGanado);
        jLabel8.setOpaque(true);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        Color colorGanado = new Color(45, 64, 89);
        jLabel8.setBackground(colorGanado);
        jLabel8.setOpaque(true);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        Color colorGanado = new Color(78, 137, 174);
        jLabel7.setBackground(colorGanado);
        jLabel7.setOpaque(true);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        Color colorGanado = new Color(45, 64, 89);
        jLabel7.setBackground(colorGanado);
        jLabel7.setOpaque(true);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:

        Color colorGanado = new Color(78, 137, 174);
        jLabel6.setBackground(colorGanado);
        jLabel6.setOpaque(true);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        Color colorGanado = new Color(45, 64, 89);
        jLabel6.setBackground(colorGanado);
        jLabel6.setOpaque(true);
    }//GEN-LAST:event_jLabel6MouseExited

    private void botonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValidarActionPerformed
        // TODO add your handling code here:
        //Comprobación de la clave
        char[] password = clave.getPassword();
        String valorClave = "";
        for (int i = 0; i < password.length; i++) {

            valorClave = valorClave + password[i];
        }

        comprobacionClave(valorClave);

    }//GEN-LAST:event_botonValidarActionPerformed

    private void claveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {

            char[] password = clave.getPassword();
            String valorClave = "";
            for (int i = 0; i < password.length; i++) {

                valorClave = valorClave + password[i];
            }

            comprobacionClave(valorClave);
        }

    }//GEN-LAST:event_claveKeyPressed

    private void TablaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPrincipalMouseClicked
        // TODO add your handling code here:

        // Evento cuando se produzca un doble click (Recoge la fila)
        if (evt.getClickCount() == 2) {

            // Recoge la fila
            int fila = TablaPrincipal.rowAtPoint(evt.getPoint());

            if (fila >= 0) {

                muestraTitulo.setText((String) TablaPrincipal.getValueAt(fila, 0));
                muestraAutor.setText((String) TablaPrincipal.getValueAt(fila, 1));
                muestraRevista.setText((String) TablaPrincipal.getValueAt(fila, 2));
                muestraEditorial.setText((String) TablaPrincipal.getValueAt(fila, 3));
                muestraCategoria.setText((String) TablaPrincipal.getValueAt(fila, 4));
                muestraNRevista.setText((String) TablaPrincipal.getValueAt(fila, 5));
                muestraAno.setText((String) TablaPrincipal.getValueAt(fila, 6));
                muestraISBN.setText((String) TablaPrincipal.getValueAt(fila, 7));
                muestraLugar.setText((String) TablaPrincipal.getValueAt(fila, 8));
                muestraDepLegal.setText((String) TablaPrincipal.getValueAt(fila, 9));
                muestraEstante.setText((String) TablaPrincipal.getValueAt(fila, 10));
                muestraUbicacion.setText((String) TablaPrincipal.getValueAt(fila,11));
                muestraSignatura.setText((String) TablaPrincipal.getValueAt(fila, 12));
            

            }

        }

    }//GEN-LAST:event_TablaPrincipalMouseClicked

    private void fieldCriterioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCriterioFocusGained
        // TODO add your handling code here:

        fieldCriterio.setText("");
    }//GEN-LAST:event_fieldCriterioFocusGained

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String filtro = String.valueOf(opcionCombo.getSelectedItem());
        ponerBusqueda(fieldCriterio.getText(), filtro);
    }//GEN-LAST:event_jButton2MouseClicked

    private void botonResetFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonResetFiltroActionPerformed

    private void botonResetFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonResetFiltroMouseClicked
        // TODO add your handling code here:      
        ponerenTabla();
    }//GEN-LAST:event_botonResetFiltroMouseClicked

    private void fieldCriterioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCriterioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String filtro = String.valueOf(opcionCombo.getSelectedItem());
            ponerBusqueda(fieldCriterio.getText(), filtro);
        }
    }//GEN-LAST:event_fieldCriterioKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JTable TablaPrincipal;
    private javax.swing.JButton botonResetFiltro;
    private javax.swing.JButton botonValidar;
    private javax.swing.JPasswordField clave;
    private javax.swing.JTextField fieldCriterio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDepLegal;
    private javax.swing.JLabel labelEstante;
    private javax.swing.JLabel labelISBN;
    private javax.swing.JLabel labelLugar;
    private javax.swing.JLabel labelNRevista;
    private javax.swing.JLabel labelRevista;
    private javax.swing.JLabel labelSignatura;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUbicacion;
    private javax.swing.JLabel muestraAno;
    private javax.swing.JLabel muestraAutor;
    private javax.swing.JLabel muestraCategoria;
    private javax.swing.JLabel muestraDepLegal;
    private javax.swing.JLabel muestraEditorial;
    private javax.swing.JLabel muestraEstante;
    private javax.swing.JLabel muestraISBN;
    private javax.swing.JLabel muestraLugar;
    private javax.swing.JLabel muestraNRevista;
    private javax.swing.JLabel muestraRevista;
    private javax.swing.JLabel muestraSignatura;
    private javax.swing.JLabel muestraTitulo;
    private javax.swing.JLabel muestraUbicacion;
    private javax.swing.JComboBox<String> opcionCombo;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JPanel panelRojoInfo;
    private javax.swing.JPanel panelSalida;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel textoClave;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    //Otras constantes y variables
    private static final String NUMEROCLAVE = "Santi667";
    int x;
    int y;

    //Método de comprobación de clave
    public void comprobacionClave(String valor) {

        if (valor.equalsIgnoreCase(NUMEROCLAVE)) {

            //conexionCorrecta(new MySQL().listadolibros());
            PanelLogin.setVisible(false);
            PanelMenu.setVisible(true);
            panelFiltro.setVisible(true);
            ponerenTabla();
            // PanelControl.setVisible(true);

        } else {

            System.out.print(valor);
            JOptionPane.showMessageDialog(null, "Clave incorrecta", "Clave Erronea", JOptionPane.ERROR_MESSAGE);

        }

    }

    public void ponerBusqueda(String valor, String filtro) {

        DefaultTableModel modelo = (DefaultTableModel) TablaPrincipal.getModel();

        ArrayList<Libros> provisional = datos.listadolibros(valor, filtro);

        limpiarTabla();

        //Recorre el listado de aviones del vector de aviones del aeropuerto de la clase <Control>
        for (int i = 0; i < provisional.size(); i++) {

            //Se crea un Array para almacenar la matrícula, origen y destino del <avión>
            String[] lista = new String[15];

            //Rellena el array con la información obtenida
            lista[0] = provisional.get(i).getTitulo();
            lista[1] = provisional.get(i).getAutor();
            lista[2] = provisional.get(i).getRevista();
            lista[3] = provisional.get(i).getEditorial();
            lista[4] = provisional.get(i).getCategoria();
            lista[5] = String.valueOf(provisional.get(i).getNrevista());
            lista[6] = String.valueOf(provisional.get(i).getAño());
            lista[7] = provisional.get(i).getISBN();
            lista[8] = provisional.get(i).getLugar();
            lista[9] = provisional.get(i).getDeposito_legal();
            lista[10] = provisional.get(i).getEstante();
            lista[11] = provisional.get(i).getUbicacion();
            lista[12] = provisional.get(i).getSignatura();
            lista[13] = provisional.get(i).getObservaciones();
            lista[14] = provisional.get(i).getInforme();

            //Añade el array a la fila de la tabla
            modelo.addRow(lista);

        }

        TablaPrincipal.setModel(modelo);

    }

    public void ponerenTabla() {

        limpiarTabla();

        DefaultTableModel modelo = (DefaultTableModel) TablaPrincipal.getModel();
        ArrayList<Libros> provisional = datos.listadolibros(null, null);

        //Recorre el listado de aviones del vector de aviones del aeropuerto de la clase <Control>
        for (int i = 0; i < provisional.size(); i++) {

            //Se crea un Array para almacenar la matrícula, origen y destino del <avión>
            String[] lista = new String[15];

            //Rellena el array con la información obtenida
            lista[0] = provisional.get(i).getTitulo();
            lista[1] = provisional.get(i).getAutor();
            lista[2] = provisional.get(i).getRevista();
            lista[3] = provisional.get(i).getEditorial();
            lista[4] = provisional.get(i).getCategoria();
            lista[5] = String.valueOf(provisional.get(i).getNrevista());
            lista[6] = String.valueOf(provisional.get(i).getAño());
            lista[7] = provisional.get(i).getISBN();
            lista[8] = provisional.get(i).getLugar();
            lista[9] = provisional.get(i).getDeposito_legal();
            lista[10] = provisional.get(i).getEstante();
            lista[11] = provisional.get(i).getUbicacion();
            lista[12] = provisional.get(i).getSignatura();
            lista[13] = provisional.get(i).getObservaciones();
            lista[14] = provisional.get(i).getInforme();

            //Añade el array a la fila de la tabla
            modelo.addRow(lista);

        }

    }

    public void limpiarTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) TablaPrincipal.getModel();
            int filas = TablaPrincipal.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

}
