/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import javax.swing.JOptionPane;
import conexiones.*;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author raulsantiago
 */
public class PanelCargaInicial extends javax.swing.JFrame {
    
    Datosalmacenados datos = null;

    /**
     * Creates new form NewJFrame
     */
    public PanelCargaInicial(Datosalmacenados datos) {
        this.datos = datos;
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelIzq = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        clave = new javax.swing.JPasswordField();
        textoClave = new javax.swing.JLabel();
        botonValidar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelRojoInfo = new javax.swing.JPanel();
        panelFiltro = new javax.swing.JPanel();
        panelTabla = new javax.swing.JPanel();
        panelSalida = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrincipal = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SanBiblioteca");
        setBackground(new java.awt.Color(153, 0, 0));
        setUndecorated(true);
        setResizable(false);

        panelIzq.setBackground(new java.awt.Color(45, 64, 89));
        panelIzq.setForeground(new java.awt.Color(255, 255, 255));

        panelTitulo.setBackground(new java.awt.Color(222, 205, 195));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-books-48.png"))); // NOI18N
        panelTitulo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        titulo.setFont(new java.awt.Font("Kohinoor Telugu", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(45, 64, 89));
        titulo.setText("SANBIBLIOTECA");
        panelTitulo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        PanelLogin.setBackground(new java.awt.Color(45, 64, 89));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clave.setText("Clavedeacceso");
        clave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                claveFocusLost(evt);
            }
        });
        PanelLogin.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 30));

        textoClave.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        textoClave.setForeground(new java.awt.Color(255, 255, 255));
        textoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneles/icons8-password-48.png"))); // NOI18N
        textoClave.setText("Clave:");
        PanelLogin.add(textoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        botonValidar.setText("Login");
        botonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValidarActionPerformed(evt);
            }
        });
        PanelLogin.add(botonValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Kefa", 3, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 205, 195));
        jLabel5.setText("Created by: Raul Santiago Prieto");
        PanelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        javax.swing.GroupLayout panelIzqLayout = new javax.swing.GroupLayout(panelIzq);
        panelIzq.setLayout(panelIzqLayout);
        panelIzqLayout.setHorizontalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzqLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIzqLayout.setVerticalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRojoInfo.setBackground(new java.awt.Color(234, 84, 85));

        javax.swing.GroupLayout panelRojoInfoLayout = new javax.swing.GroupLayout(panelRojoInfo);
        panelRojoInfo.setLayout(panelRojoInfoLayout);
        panelRojoInfoLayout.setHorizontalGroup(
            panelRojoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        panelRojoInfoLayout.setVerticalGroup(
            panelRojoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        panelTabla.setBackground(new java.awt.Color(229, 229, 229));

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        panelSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 64, 89));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelSalidaLayout = new javax.swing.GroupLayout(panelSalida);
        panelSalida.setLayout(panelSalidaLayout);
        panelSalidaLayout.setHorizontalGroup(
            panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalidaLayout.createSequentialGroup()
                .addContainerGap(846, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(22, 22, 22))
        );
        panelSalidaLayout.setVerticalGroup(
            panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalidaLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        TablaPrincipal.setBackground(new java.awt.Color(229, 229, 229));
        TablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Revista", "Editorial", "Categoria", "Nº Revista", "Año", "ISBN", "Lugar", "Deposito leg.", "Estante", "Ubicación", "Signatura", "Observaciones", "Informe"
            }
        ));
        jScrollPane1.setViewportView(TablaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRojoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRojoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(1200, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void claveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_claveFocusLost

        char[] password = clave.getPassword();

        if (password.length < 5 && password.length > 10) {

            clave.setBackground(Color.red);
        }
    }//GEN-LAST:event_claveFocusLost

    private void botonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValidarActionPerformed
        // TODO add your handling code here:
        //Comprobación de la clave     
        char[] password = clave.getPassword();
        String valorClave = "";
        for (int i = 0; i < password.length; i++) {

            valorClave = valorClave + password[i];
        }

        comprobacionClave(valorClave);


    }//GEN-LAST:event_botonValidarActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabel4MousePressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JTable TablaPrincipal;
    private javax.swing.JButton botonValidar;
    private javax.swing.JPasswordField clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JPanel panelRojoInfo;
    private javax.swing.JPanel panelSalida;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel textoClave;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    //Otras constantes y variables
    private static final String NUMEROCLAVE = "Santi667";
    int x;
    int y;
Bibliotecaprincipal biblio =   new Bibliotecaprincipal(new Datosalmacenados());
    //Método de comprobación de clave
    public void comprobacionClave(String valor) {

        if (valor.equalsIgnoreCase(NUMEROCLAVE)) {

            //conexionCorrecta(new MySQL().listadolibros());
            PanelLogin.setVisible(false);
            ponerenTabla();
           // PanelControl.setVisible(true);

        } else {

            System.out.print(valor);
            JOptionPane.showMessageDialog(null, "Clave incorrecta", "Clave Erronea", JOptionPane.ERROR_MESSAGE);

        }

    }


    
    public void ponerenTabla() {
        
         
          DefaultTableModel modelo = (DefaultTableModel) TablaPrincipal.getModel();

        //Recorre el listado de aviones del vector de aviones del aeropuerto de la clase <Control>
        for (int i = 0; i < datos.listado.size(); i++) {

            //Se crea un Array para almacenar la matrícula, origen y destino del <avión>
            String[] lista = new String[15];

           
            //Rellena el array con la información obtenida
            lista[0] = datos.listado.get(i).getTitulo();
            lista[1] = datos.listado.get(i).getAutor();
            lista[2] = datos.listado.get(i).getRevista();
            lista[3] = datos.listado.get(i).getEditorial();
            lista[4] = datos.listado.get(i).getCategoria();
            lista[5] = String.valueOf(datos.listado.get(i).getNrevista());
            lista[6] = String.valueOf(datos.listado.get(i).getAño());
            lista[7] = datos.listado.get(i).getISBN();
            lista[8] = datos.listado.get(i).getLugar();
            lista[9] = datos.listado.get(i).getDeposito_legal();
            lista[10] = datos.listado.get(i).getEstante();
            lista[11] = datos.listado.get(i).getUbicacion();
            lista[12] = datos.listado.get(i).getSignatura();
            lista[13] = datos.listado.get(i).getObservaciones();
            lista[14] = datos.listado.get(i).getInforme();

            
            //Añade el array a la fila de la tabla
          modelo.addRow(lista);
            

        }
        
        TablaPrincipal.setModel(modelo);

    }
    
    

}
